services:
  app:
    build:
      context: https://github.com/ITLab-CC/plane-middleware-discord.git
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env